# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-08 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedimento', models.IntegerField(null=True, verbose_name='pedimento')),
                ('numProyecto', models.CharField(max_length=200, null=True, verbose_name='Numero de proyecto')),
                ('localizacion', models.CharField(max_length=200, null=True, verbose_name=b'Localizacion')),
                ('ordenCompra', models.CharField(max_length=15, null=True, verbose_name='Orden de compra')),
                ('modelo', models.CharField(max_length=200, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(max_length=200, null=True, verbose_name='Serie')),
                ('origen', models.CharField(max_length=200, null=True, verbose_name='Origen')),
                ('precio', models.CharField(max_length=200, null=True, verbose_name='Precio')),
                ('tipoCambio', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Tipo de cambio')),
                ('fecha_ingreso', models.DateTimeField(verbose_name='fecha de ingreso')),
                ('fecha_pedimento', models.DateTimeField(verbose_name='fecha de pedimento')),
                ('descripcion', models.CharField(max_length=500, null=True, verbose_name='Descripcion')),
                ('jssID', models.CharField(max_length=200, null=True, verbose_name='JSS ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='fecha_inicio')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marca.Marca')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
