# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-19 00:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedimento', models.IntegerField(max_length=20, null=True, verbose_name='nombre(s)')),
                ('numProyecto', models.CharField(max_length=200, null=True, verbose_name='puesto')),
                ('localizacion', models.CharField(max_length=200, null=True, verbose_name=b'fecha_nacimiento')),
                ('ordenCompra', models.CharField(max_length=15, null=True, verbose_name='telefono')),
                ('marca', models.CharField(max_length=200, null=True, verbose_name='correo')),
                ('modelo', models.CharField(max_length=200, null=True, verbose_name='Direccion')),
                ('serie', models.CharField(max_length=200, null=True, verbose_name='Direccion')),
                ('origen', models.CharField(max_length=200, null=True, verbose_name='Direccion')),
                ('precio', models.CharField(max_length=200, null=True, verbose_name='Direccion')),
                ('tipoCambio', models.IntegerField(max_length=200, null=True, verbose_name='Direccion')),
                ('fechaIngreso', models.DateTimeField(verbose_name='fecha_inicio')),
                ('fechaPedimento', models.DateTimeField(verbose_name='fecha_inicio')),
                ('descripcion', models.CharField(max_length=500, null=True, verbose_name='Direccion')),
                ('jssID', models.CharField(max_length=200, null=True, verbose_name='Direccion')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='fecha_inicio')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
