# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-19 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='pedimento',
            field=models.IntegerField(null=True, verbose_name='nombre(s)'),
        ),
        migrations.AlterField(
            model_name='main',
            name='tipoCambio',
            field=models.IntegerField(null=True, verbose_name='Direccion'),
        ),
    ]
