# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-02 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to=b'main', verbose_name=b'Imagen'),
        ),
        migrations.AddField(
            model_name='main',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to=b'main', verbose_name=b'Imagen2'),
        ),
    ]
