# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-19 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180418_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='fechaIngreso',
            new_name='fecha_ingreso',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='fechaPedimento',
            new_name='fecha_pedimento',
        ),
    ]
