# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-10 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180702_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='main',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, verbose_name='fecha_inicio'),
        ),
        migrations.AlterField(
            model_name='main',
            name='fecha_pedimento',
            field=models.DateField(verbose_name='fecha de pedimento'),
        ),
    ]
