# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-25 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180418_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='descripcion',
            field=models.CharField(max_length=500, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='main',
            name='fecha_ingreso',
            field=models.DateTimeField(verbose_name='fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='main',
            name='fecha_pedimento',
            field=models.DateTimeField(verbose_name='fecha de pedimento'),
        ),
        migrations.AlterField(
            model_name='main',
            name='jssID',
            field=models.CharField(max_length=200, null=True, verbose_name='JSS ID'),
        ),
        migrations.AlterField(
            model_name='main',
            name='localizacion',
            field=models.CharField(max_length=200, null=True, verbose_name=b'Localizacion'),
        ),
        migrations.AlterField(
            model_name='main',
            name='marca',
            field=models.CharField(max_length=200, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='main',
            name='modelo',
            field=models.CharField(max_length=200, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='main',
            name='numProyecto',
            field=models.CharField(max_length=200, null=True, verbose_name='Numero de proyecto'),
        ),
        migrations.AlterField(
            model_name='main',
            name='ordenCompra',
            field=models.CharField(max_length=15, null=True, verbose_name='Orden de compra'),
        ),
        migrations.AlterField(
            model_name='main',
            name='origen',
            field=models.CharField(max_length=200, null=True, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='main',
            name='pedimento',
            field=models.IntegerField(null=True, verbose_name='pedimento'),
        ),
        migrations.AlterField(
            model_name='main',
            name='precio',
            field=models.CharField(max_length=200, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='main',
            name='serie',
            field=models.CharField(max_length=200, null=True, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='main',
            name='tipoCambio',
            field=models.IntegerField(null=True, verbose_name='Tipo de cambio'),
        ),
    ]
