# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-22 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180425_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='tipoCambio',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Tipo de cambio'),
        ),
    ]
