# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-16 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180710_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='main',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='main',
            name='jssID',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='JSS ID'),
        ),
        migrations.AlterField(
            model_name='main',
            name='localizacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Localizacion'),
        ),
        migrations.AlterField(
            model_name='main',
            name='modelo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='main',
            name='numProyecto',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Numero de proyecto'),
        ),
        migrations.AlterField(
            model_name='main',
            name='ordenCompra',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Orden de compra'),
        ),
        migrations.AlterField(
            model_name='main',
            name='origen',
            field=models.CharField(blank=True, choices=[(b'Cd. Juarez', b'Cd. Juarez'), (b'Valle Hermoso', b'Valle Hermoso')], max_length=200, null=True, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='main',
            name='pedimento',
            field=models.IntegerField(blank=True, null=True, verbose_name='pedimento'),
        ),
        migrations.AlterField(
            model_name='main',
            name='precio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='main',
            name='serie',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='main',
            name='tipoCambio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tipo de cambio'),
        ),
        migrations.AlterField(
            model_name='main',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
