# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name=b'Nombre')),
                ('observaciones', models.CharField(max_length=200, null=True, verbose_name='Observaciones')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='fecha_inicio')),
            ],
        ),
    ]
